# Generated by Django 2.2.6 on 2019-10-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20191028_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='honor_applied',
            field=models.BooleanField(default='False', editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_targeted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
