# Generated by Django 2.2.6 on 2019-11-05 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20191029_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=3), help_text='Dauer'),
        ),
        migrations.AlterField(
            model_name='uservalues',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
