# Generated by Django 2.2.7 on 2019-11-15 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20191105_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Dauer'),
        ),
    ]
