# Generated by Django 2.2.7 on 2019-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20191115_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.DateTimeField(help_text='Erstellt am'),
        ),
    ]
