# Generated by Django 2.2.7 on 2019-11-19 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_auto_20191119_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Erstellt am'),
        ),
    ]
