# Generated by Django 2.2.7 on 2019-11-25 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0010_issuecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='administrated_groups', to=settings.AUTH_USER_MODEL)),
                ('initiates', models.ManyToManyField(related_name='requested_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='ehre_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
