# Generated by Django 2.2.7 on 2019-11-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Erstellt am'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Gang', help_text='Der Name dieser Gang', max_length=256),
        ),
    ]
