# Generated by Django 2.2.7 on 2019-11-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_auto_20191126_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='counter.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='initiates',
            field=models.ManyToManyField(blank=True, related_name='requested_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
