# Generated by Django 2.2.7 on 2019-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(default='', help_text='Betreff', max_length=256)),
                ('text', models.TextField(help_text="Was gibt's?")),
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Erstellt am')),
            ],
        ),
    ]
